[General]
ApplicationVersion = '''0.4.4'''
FreeSpaceSearch = '''000200'''
FreeSpaceBuffer = '''100'''
NextExportID = '''0'''
ShowRawIVByteForTrainer = False

#################################
#################################
#################################
#################################
#################################
#################################
#################################
#################################
